services:
  # Готовый браузер (скачивается быстро, собирать не нужно)
  chrome_server:
    image: selenium/standalone-chrome:latest
    shm_size: 2gb
    ports:
      - "4444:4444"

  ui_tests:
    build: .
    image: ui:v1
    depends_on:
      - chrome_server
    environment:
      - SELENIUM_REMOTE_URL=http://chrome_server:4444/wd/hub
      # Прокидываем логины/пароли
      - ADMIN_LOGIN=${ADMIN_LOGIN}
      - ADMIN_PASSWORD=${ADMIN_PASSWORD}
      - FRIEND_LOGIN=${FRIEND_LOGIN}
      - FRIEND_PASSWORD=${FRIEND_PASSWORD}
      - FRIEND_EMAIL=${FRIEND_EMAIL}
      - TOKEN=${TOKEN}
      - CHAT_ID=${CHAT_ID}
    volumes:
      - .:/usr/workspace
    command: pytest -sv --alluredir=report --ignore=gh-pages-dir

  report:
    image: ui:v1
    volumes:
      - .:/usr/workspace
    working_dir: /usr/workspace
    command: allure generate report -o allure-report --clean