[pytest]
# Настройки запуска (добавление retry)
addopts = -sv --alluredir=report --reruns 2 --reruns-delay 1

# Регистрация маркеров, чтобы избежать warnings
markers =
    smoke: mark test as a smoke test (critical path)
    regression: mark test as a regression test

